/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
#include "nsISupports.idl"
#include "nsIDOMWindow.idl"

/**
 * An optional interface for embedding clients wishing to receive
 * notifications for when a tooltip should be displayed or removed.
 * The embedder implements this interface on the web browser chrome
 * object associated with the window that notifications are required
 * for.
 *
 * @see nsIEmbedAppService
 */

%{C++
#include "nsStringGlue.h" // needed for AString -> nsAString, unfortunately
#include "mozilla/layers/GeckoContentController.h"
%}

[ptr] native GeckoContentController(mozilla::layers::GeckoContentController);

[scriptable, uuid(41dc842c-6934-11e2-9124-933bf9a3f6a9)]
interface nsIEmbedMessageListener : nsISupports
{
    void onMessageReceived(in string messageName, in wstring message);
};

[scriptable, uuid(3c61976a-710b-11e2-a4a0-1354c757920d)]
interface nsIEmbedAppService : nsISupports
{
    void sendAsyncMessage(in uint32_t aId, in wstring messageName, in wstring message);
    void sendSyncMessage(in uint32_t aId, in wstring messageName, in wstring message,
                         out AString retval);
    void GetIDByWindow(in nsIDOMWindow aWin, out uint32_t aId);
    void addMessageListener(in string name, in nsIEmbedMessageListener listener);
    void removeMessageListener(in string name, in nsIEmbedMessageListener listener);
    void enterSecureJSContext();
    void leaveSecureJSContext();
    [noscript] void addContentListener(in uint32_t aId, in GeckoContentController listener);
    [noscript] void removeContentListener(in uint32_t aId, in GeckoContentController listener);
};
